CREATE TABLE IF NOT EXISTS post_analytics (
    id SERIAL PRIMARY KEY,
    post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    ip_address VARCHAR(45) NOT NULL,
    user_agent TEXT,
    is_logged_in BOOLEAN DEFAULT FALSE,
    view_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
